name: "Main workflow"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qa:
    uses: ./.github/workflows/_qa.yaml
    secrets: inherit
    with:
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
