name: "Main workflow"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qa:
    uses: ./.github/workflows/_qa.yaml
    with:
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}

  deploy:
    if: ${{ github.ref_name == 'main' || github.event_name == 'workflow_dispatch' }}
    needs: qa
    uses: ./.github/workflows/_deploy.yaml
    with:
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
